# Netlify Configuration for Monorepo
[build]
  # Base directory for the Next.js app
  base = "frontend"
  
  # Build command
  command = "npm run build"
  
  # Directory to publish (Next.js output)
  publish = "frontend/.next"
  
  # Functions directory for API routes
  functions = "frontend/.next/server"

# Node.js version
[build.environment]
  NODE_VERSION = "18"

# Netlify Next.js Plugin Configuration
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
